export const lightTheme = {
  palette: {
    themePrimary: '#0078d4',
    themeLighterAlt: '#eff6fc',
    themeLighter: '#deecf9',
    themeLight: '#c7e0f4',
    themeTertiary: '#71afe5',
    themeSecondary: '#2b88d8',
    themeDarkAlt: '#106ebe',
    themeDark: '#005a9e',
    themeDarker: '#004578',
    neutralLighterAlt: '#faf9f8',
    neutralLighter: '#f3f2f1',
    neutralLight: '#edebe9',
    neutralQuaternaryAlt: '#e1dfdd',
    neutralQuaternary: '#d0d0d0',
    neutralTertiaryAlt: '#c8c6c4',
    neutralTertiary: '#a19f9d',
    neutralSecondary: '#605e5c',
    neutralPrimaryAlt: '#3b3a39',
    neutralPrimary: '#323130',
    neutralDark: '#201f1e',
    black: '#000000',
    white: '#ffffff',
  },
};
export const darkTheme = {
  palette:  {
    themePrimary: '#9d9eeb',
    themeLighterAlt: '#fbfbfe',
    themeLighter: '#eeeffc',
    themeLight: '#e0e1f9',
    themeTertiary: '#c3c3f3',
    themeSecondary: '#a8a9ed',
    themeDarkAlt: '#8d8fd3',
    themeDark: '#7778b2',
    themeDarker: '#585983',
    neutralLighterAlt: '#2e2e54',
    neutralLighter: '#2d2d53',
    neutralLight: '#2b2b50',
    neutralQuaternaryAlt: '#28284a',
    neutralQuaternary: '#262647',
    neutralTertiaryAlt: '#252544',
    neutralTertiary: '#e0e0e0',
    neutralSecondary: '#e5e5e5',
    neutralSecondaryAlt: '#e5e5e5',
    neutralPrimaryAlt: '#eaeaea',
    neutralPrimary: '#d1d1d1',
    neutralDark: '#f4f4f4',
    black: '#f9f9f9',
    white: '#2f2f57',
  },
};

export const headerTheme = {
  palette: {
    themePrimary: '#9d9eeb',
    themeLighterAlt: '#fbfbfe',
    themeLighter: '#eeeffc',
    themeLight: '#e0e1f9',
    themeTertiary: '#c3c3f3',
    themeSecondary: '#a8a9ed',
    themeDarkAlt: '#8d8fd3',
    themeDark: '#7778b2',
    themeDarker: '#585983',
    neutralLighterAlt: '#2e2e54',
    neutralLighter: '#2d2d53',
    neutralLight: '#2b2b50',
    neutralQuaternaryAlt: '#28284a',
    neutralQuaternary: '#262647',
    neutralTertiaryAlt: '#252544',
    neutralTertiary: '#e0e0e0',
    neutralSecondary: '#e5e5e5',
    neutralSecondaryAlt: '#e5e5e5',
    neutralPrimaryAlt: '#eaeaea',
    neutralPrimary: '#d1d1d1',
    neutralDark: '#f4f4f4',
    black: '#f9f9f9',
    white: '#2f2f57',
  }
};

/* Standard Dark Theme
palette: {
    themePrimary: "#a3a5ff",
    themeLighterAlt: "#adafff",
    themeLighter: "#b7b9ff",
    themeLight: "#c1c3ff",
    themeTertiary: "#ccccff",
    themeSecondary: "#d6d6ff",
    themeDarkAlt: "#e0e0ff",
    themeDark: "#eaeaff",
    themeDarker: "#f4f4ff",
    neutralLighterAlt: "#464646",
    neutralLighter: "#4d4d4d",
    neutralLight: "#595959",
    neutralQuaternaryAlt: "#616161",
    neutralQuaternary: "#676767",
    neutralTertiaryAlt: "#818181",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#3d3d3d",
  }
*/
