export const lightTheme = {
  palette: {
    themePrimary: "#6667ab",
    themeLighterAlt: "#f8f8fc",
    themeLighter: "#e2e2f2",
    themeLight: "#cacbe6",
    themeTertiary: "#9b9ccd",
    themeSecondary: "#7576b5",
    themeDarkAlt: "#5c5d9a",
    themeDark: "#4e4f82",
    themeDarker: "#393a60",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
};
export const darkTheme = {
  palette: {
    themePrimary: "#9d9eeb",
    themeLighterAlt: "#060609",
    themeLighter: "#191926",
    themeLight: "#2f3046",
    themeTertiary: "#5e5f8d",
    themeSecondary: "#8a8bce",
    themeDarkAlt: "#a6a8ed",
    themeDark: "#b3b4ef",
    themeDarker: "#c7c7f4",
    neutralLighterAlt: "#35355e",
    neutralLighter: "#3a3b65",
    neutralLight: "#43446f",
    neutralQuaternaryAlt: "#494a76",
    neutralQuaternary: "#4f4f7b",
    neutralTertiaryAlt: "#666791",
    neutralTertiary: "#e4e4e4",
    neutralSecondary: "#e8e8e8",
    neutralPrimaryAlt: "#ededed",
    neutralPrimary: "#d6d6d6",
    neutralDark: "#f6f6f6",
    black: "#fafafa",
    white: "#2f2f57",
  },
};

/* Standard Dark Theme
palette: {
    themePrimary: "#a3a5ff",
    themeLighterAlt: "#adafff",
    themeLighter: "#b7b9ff",
    themeLight: "#c1c3ff",
    themeTertiary: "#ccccff",
    themeSecondary: "#d6d6ff",
    themeDarkAlt: "#e0e0ff",
    themeDark: "#eaeaff",
    themeDarker: "#f4f4ff",
    neutralLighterAlt: "#464646",
    neutralLighter: "#4d4d4d",
    neutralLight: "#595959",
    neutralQuaternaryAlt: "#616161",
    neutralQuaternary: "#676767",
    neutralTertiaryAlt: "#818181",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#3d3d3d",
  }
*/
